# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-08-18 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    replaces = [('facilities', '0002_auto_20190627_0852'), ('facilities', '0003_auto_20190728_0905'), ('facilities', '0004_auto_20190728_1949'), ('facilities', '0005_auto_20190728_2014'), ('facilities', '0006_auto_20190728_2153'), ('facilities', '0007_auto_20190818_0221'), ('facilities', '0008_auto_20190818_0841')]

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Identifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.CharField(max_length=64)),
                ('context', models.CharField(max_length=64)),
                ('external_id', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='orgunit',
            name='identifiers',
            field=models.ManyToManyField(to='facilities.Identifier'),
        ),
        migrations.AlterField(
            model_name='orgunit',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='identifier',
            unique_together=set([('agency', 'context', 'external_id')]),
        ),
        migrations.AlterField(
            model_name='orgunit',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='orgunit',
            name='authority',
            field=models.CharField(choices=[('AIC', 'AIC'), ('CAFU', 'CAFU'), ('CBO', 'CBO'), ('GOVT', 'Government'), ('MOES', 'MOES'), ('MOH', 'MOH'), ('NGO', 'NGO'), ('PRIVATE', 'Private'), ('SDA', 'SDA'), ('SOS', 'SOS'), ('TASO', 'TASO'), ('UBTS', 'UBTS'), ('UCBHCA', 'UCBHCA'), ('UCMB', 'UCMB'), ('UMMB', 'UMMB'), ('UNHCR', 'UNHCR'), ('UOMB', 'UOMB'), ('UPDF', 'UPDF'), ('UPF', 'UPF'), ('UPMB', 'UPMB'), ('UPS', 'UPS'), ('URHB', 'URHB')], db_index=True, default='GOVT', max_length=16),
        ),
        migrations.AddField(
            model_name='orgunit',
            name='orgunit_type',
            field=models.CharField(choices=[('ADMIN', 'Administrative Unit'), ('BCDP', 'Blood Collection and Distribution Point'), ('CLINIC', 'Clinic'), ('HC II', 'HC II'), ('HC III', 'HC III'), ('HC IV', 'HC IV'), ('HOSPITAL', 'General Hospital'), ('NBB', 'National Blood Bank'), ('NRH', 'National Referral Hospital'), ('RBB', 'Regional Blood Bank'), ('RRH', 'Regional Referral Hospital'), ('SC', 'Special Clinic')], db_index=True, default='ADMIN', max_length=16, verbose_name='type'),
        ),
        migrations.AddField(
            model_name='orgunit',
            name='ownership',
            field=models.CharField(choices=[('GOVT', 'Government'), ('PNFP', 'PNFP'), ('PFP', 'PFP')], db_index=True, default='GOVT', max_length=16),
        ),
        migrations.AlterField(
            model_name='orgunit',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='orgunit',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AddField(
            model_name='orgunit',
            name='geometry_str',
            field=models.TextField(null=True, verbose_name='geometry (GeoJSON string)'),
        ),
    ]
