# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-11-19 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_auto_20190818_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgunit',
            name='geometry_str',
            field=models.TextField(blank=True, default='', verbose_name='geometry (GeoJSON string)'),
        ),
    ]
